name: adkari
description: A new Flutter project.

publish_to: 'none'


environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
    - images/
  fonts:
     - family: Raleway
       fonts:
         - asset: fonts/Abd-Regular.otf
         - asset: fonts/Abd-Bold.otf
           weight: 700


